<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No options</name>
   <tag></tag>
   <elementGuidId>f81a6794-8ff0-4a53-a534-e8d8209e7959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-instance-id-project-listbox']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.select2-selection__menu-notice.select2-selection__menu-notice--no-options.css-1gl4k7y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5811eff-469e-4508-b5da-6fb96667becb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__menu-notice select2-selection__menu-notice--no-options css-1gl4k7y</value>
      <webElementGuid>4d152def-7022-47e5-a42e-6faa2b8e0ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No options</value>
      <webElementGuid>233d6c83-4f39-4b4a-9a04-7d59279282a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-instance-id-project-listbox&quot;)/div[@class=&quot;select2-selection__menu-list css-v45c7s&quot;]/div[@class=&quot;select2-selection__menu-notice select2-selection__menu-notice--no-options css-1gl4k7y&quot;]</value>
      <webElementGuid>eebf8aa5-dbe6-4824-b13b-36170744e9c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-project-listbox']/div/div</value>
      <webElementGuid>f0f9ab6c-d345-4e96-8766-d9896b9d33ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[10]</value>
      <webElementGuid>8d15d180-96f5-4022-a9ca-460745857b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[1]</value>
      <webElementGuid>a8bbeca9-1386-4f59-a932-6bd1520b6043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No options']/parent::*</value>
      <webElementGuid>135f254b-9f8c-4c3a-a98d-38ab30b33a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>078b9112-e7e9-46df-b2c1-c3462a9523c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No options' or . = 'No options')]</value>
      <webElementGuid>f4837dab-f6cf-4db2-b75f-55c8af4c3ba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
