<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__estimatedDate</name>
   <tag></tag>
   <elementGuidId>5a5025be-43fb-45e6-affc-00c6402a220f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='estimatedDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;estimatedDate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1ac327e-ebe7-4ea0-b5d6-67305a64275a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker</name>
      <type>Main</type>
      <value>[object Undefined]</value>
      <webElementGuid>4e9fd159-c4dd-40f6-98eb-48441033cb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2023-01-06</value>
      <webElementGuid>1a1b53bd-4a6d-41ae-a623-6f62b09f16d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estimatedDate</value>
      <webElementGuid>0ae2f592-21c5-4fb9-b2c6-1ddbd7717495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>5101bc6c-c47c-44c6-a9f2-37c31bfb5fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border rounded p-2 h-12 border-gray-200 outline-none text-black undefined</value>
      <webElementGuid>c1ee2da7-8fa2-46b7-9c65-3062bad3ced4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex-1 flex overflow-hidden&quot;]/div[@class=&quot;flex-1 overflow-y-auto main-content py-10 px-4 md:px-8 scrollbar scrollbar_for_firefox&quot;]/div[@class=&quot;flex justify-center undefined&quot;]/div[@class=&quot;block p-6 rounded-lg shadow-lg bg-white min-w-full border border-gray-200&quot;]/form[1]/div[@class=&quot;grid grid-cols-1 gap-6 mt-5 md:grid-cols-2&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/input[@class=&quot;w-full border rounded p-2 h-12 border-gray-200 outline-none text-black undefined&quot;]</value>
      <webElementGuid>dc3ced56-e0c9-48f7-b004-d15c6aaeb135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='estimatedDate']</value>
      <webElementGuid>330be975-f96d-4924-88ed-ed266fdff01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[2]/div/form/div[4]/div/input</value>
      <webElementGuid>4ad367df-fdbb-4cb0-8ae3-40c1565dc4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>d35e3565-173f-44a3-8d67-bcde711ed970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'estimatedDate' and @type = 'date']</value>
      <webElementGuid>62bd83f3-5f04-4e45-8b54-c3693e050030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
