<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59</name>
   <tag></tag>
   <elementGuidId>31b06c34-324c-4baf-b4f8-5c7f05f20a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dddf9de5-ddca-4894-8531-d8b17acedb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none bg-primary-50 addRateInputTextColor appearance-none w-[70px]</value>
      <webElementGuid>6ebc6be8-6d56-4045-bf7f-11ff95e1b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59</value>
      <webElementGuid>2132aa13-3058-43dd-a10f-d7638fa12f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59</value>
      <webElementGuid>ca319df9-0259-4e93-bd28-cf6efdc42b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>866c238c-a1be-4834-b9c3-e8953e9d1d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.001</value>
      <webElementGuid>be3dfd55-e428-47e8-ab7b-dcdf680429bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59&quot;)</value>
      <webElementGuid>a52fd99e-abc9-4ee7-8261-ba8d0a7e5a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59']</value>
      <webElementGuid>02006ae8-75fd-481e-91d0-02a09d4ede93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='image-section']/div[2]/form/div/div[2]/div[2]/input</value>
      <webElementGuid>f86cc821-530f-421e-920d-d50a19819bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ac0e0f1f-4882-4f9f-81f4-5fc8dd989346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59' and @id = 'rate__ad32c9d0-90ca-4b38-80ab-c96002db7b59' and @type = 'number']</value>
      <webElementGuid>772434ce-2670-43bc-ad1f-43f36805c992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
