<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Item</name>
   <tag></tag>
   <elementGuidId>2cad6f69-caea-4d9c-9e84-6e3e0d1f7679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51227dea-b493-49bd-831d-228a501941f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  button button-Primary flex justify-center items-center bg-primary-500 h-10 w-auto  rounded font-semibold text-sm text-Basic-0 px-2 md:px-6 undefined  </value>
      <webElementGuid>ee9d52e4-b15c-4ba3-8017-d6ecd42d07de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d582950d-3d8f-48a4-87b9-b31ba5541444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Item</value>
      <webElementGuid>0eeb24fc-4b1f-40a7-a35f-3edc72bc9da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex-1 flex overflow-hidden&quot;]/div[@class=&quot;flex-1 overflow-y-auto main-content py-10 px-4 md:px-8 scrollbar scrollbar_for_firefox&quot;]/div[@class=&quot;flex justify-center undefined&quot;]/div[@class=&quot;block p-6 rounded-lg shadow-lg bg-white min-w-full border border-gray-200&quot;]/div[@class=&quot;flex items-center justify-between pt-11&quot;]/div[@class=&quot;flex flex-row gap-2&quot;]/div[1]/button[@class=&quot;button button-Primary flex justify-center items-center bg-primary-500 h-10 w-auto  rounded font-semibold text-sm text-Basic-0 px-2 md:px-6 undefined&quot;]</value>
      <webElementGuid>d9978ad3-2c5c-4a45-885c-552aed02e47a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>a435014c-c8a3-4a8c-b9b4-f20540e4463f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/button</value>
      <webElementGuid>ff7483e0-4518-4138-92db-55cbd9fc1fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kindly add your item(s)'])[1]/following::button[1]</value>
      <webElementGuid>aef64287-e87f-44c5-bb16-93bb7444b860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[2]/following::button[1]</value>
      <webElementGuid>8c2a65fe-9985-4b76-be44-31cb16503869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item'])[2]/preceding::button[1]</value>
      <webElementGuid>2be722e5-ec88-4b5f-bb6f-3000096efa74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Item']/parent::*</value>
      <webElementGuid>204e1202-e4a2-4e6f-ac29-95930d68e570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>97d03c46-a332-48e1-a952-a83c3cca50c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Add Item' or . = 'Add Item')]</value>
      <webElementGuid>7dd8de35-337d-4763-a006-ef2f4a383198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
