<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Generate RFQ</name>
   <tag></tag>
   <elementGuidId>a2e3699c-df68-4546-87fe-572ace11940e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d279741-2b5c-470c-a8ba-9015d630305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ml-8 button button-Ghost text-primary-500 border border-primary-500 w-auto flex justify-center items-center h-10 rounded font-semibold text-sm  px-2 md:px-6 undefined  </value>
      <webElementGuid>a06d70a3-1899-45b8-a9eb-fa74a1fae88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f1d35019-a17e-48d1-872a-47b58ee17859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate RFQ</value>
      <webElementGuid>5ee8b42b-f288-4307-aa41-238c35fa1fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex-1 flex overflow-hidden&quot;]/div[@class=&quot;flex-1 overflow-y-auto main-content py-10 px-4 md:px-8 scrollbar scrollbar_for_firefox&quot;]/div[@class=&quot;flex justify-center undefined&quot;]/div[@class=&quot;block p-6 rounded-lg shadow-lg bg-white min-w-full border border-gray-200&quot;]/div[@class=&quot;flex items-center justify-between pt-11&quot;]/div[@class=&quot;flex flex-row gap-2&quot;]/div[2]/button[@class=&quot;ml-8 button button-Ghost text-primary-500 border border-primary-500 w-auto flex justify-center items-center h-10 rounded font-semibold text-sm  px-2 md:px-6 undefined&quot;]</value>
      <webElementGuid>266c038a-abdf-462e-a4ed-682d67cb492f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>90451fcc-1cb6-42e1-ae25-953b1cc5fab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>53153c04-3e2c-4559-94e6-c4bd1049157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item'])[1]/following::button[1]</value>
      <webElementGuid>ede6e6fb-4b6f-4568-961e-ece693c8ed6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kindly add your item(s)'])[1]/following::button[2]</value>
      <webElementGuid>365c9394-e31d-4a58-b927-c88479842003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Item'])[2]/preceding::button[1]</value>
      <webElementGuid>64cecf0a-7c09-49e5-98df-82f40e154cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generate RFQ']/parent::*</value>
      <webElementGuid>4ca3023b-aeb2-4179-9464-96c0f454c083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>47a99896-3a6d-43f2-a0ca-9e7f7e1a89b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Generate RFQ' or . = 'Generate RFQ')]</value>
      <webElementGuid>19387b03-3b31-4282-9ab2-1d54100d2210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
