<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__quantity</name>
   <tag></tag>
   <elementGuidId>1dfbfc31-f122-4c8b-95b6-1ae1c441dc28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3afd68d5-fef3-4354-bc83-027e0f0c8083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>730c354a-9be3-4daa-ab50-721b4a3dcf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>6b346a85-acfa-4568-bfdb-6e4bddfa0ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>408f91bf-8ee8-4633-bb69-751f5b4e673d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Quantity</value>
      <webElementGuid>a15234ce-deb4-4a73-9879-eef0a914b0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined bg-white textField w-full p-3 text-black border rounded outline-none text-sm transition duration-150 ease-in-out font-normal h-12 border-solid focus:border-2 focus:border-primary-400  placeholder-iron-gray focus:outline-none placeholder-[#A6B0CF]  border-gray-200 hover:border-gray-400 focus:border-error</value>
      <webElementGuid>40a55b37-decc-489b-ba02-f3c15a2ade1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity&quot;)</value>
      <webElementGuid>4e5e18bc-11c4-44f7-a951-a64a5d0281f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity']</value>
      <webElementGuid>b233d2d4-2e3c-449a-94c1-a0fe842e20aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/form/div[3]/div[2]/input</value>
      <webElementGuid>8b91f1d0-a996-40ce-9107-335001643444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>abafaa6b-9fad-4956-b823-12a6145ad8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'quantity' and @id = 'quantity' and @placeholder = 'Quantity']</value>
      <webElementGuid>cf3efd01-aaba-441b-a249-0b24a1912753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
