<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Vendor Legal</name>
   <tag></tag>
   <elementGuidId>1436635a-a528-4441-87d5-ae5f31c168c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-instance-id-vendor-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-instance-id-vendor-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a56eef66-2e0b-485e-be29-c42571d02ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__option select2-selection__option--is-focused css-1dqdw33-option</value>
      <webElementGuid>aa23ee04-64cc-49a0-9880-741109ecbce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e8a722e-8121-433e-a34a-bcea01159e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-instance-id-vendor-option-0</value>
      <webElementGuid>0d8751ae-e86b-4745-a782-3524c38ce298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7a5af155-5ffc-431b-bf01-c763801f614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Vendor Legal</value>
      <webElementGuid>bef5741d-eca4-4427-b4ef-2a45c3f55afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-instance-id-vendor-option-0&quot;)</value>
      <webElementGuid>bc1b6d94-5e63-466a-bd29-200f888c11c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-vendor-option-0']</value>
      <webElementGuid>cb6bc967-070a-485a-8237-947d293ee056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-vendor-listbox']/div/div</value>
      <webElementGuid>bdbe84f5-c3c8-4f81-9f5b-b21f70744bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[10]</value>
      <webElementGuid>c1ba604e-6a85-45fe-8065-10a94bc07791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[1]</value>
      <webElementGuid>9f6f7b05-c92d-49d5-9931-7a452cf785ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Vendor Legal']/parent::*</value>
      <webElementGuid>df41a5c2-49bf-4ccf-9fe2-b6956f8afbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>a747d373-3ca8-48e4-b3e0-7d5f7ad5eca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-instance-id-vendor-option-0' and (text() = 'Test Vendor Legal' or . = 'Test Vendor Legal')]</value>
      <webElementGuid>6daf0d3f-3bc3-4400-a0a1-eca1b3c2089d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
