<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terms_ANuIbb IdAqtf</name>
   <tag></tag>
   <elementGuidId>b0dcad97-ecc4-4c5d-bcee-ccd5fe5e6aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='initialView']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ANuIbb.IdAqtf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>efc709c9-fa61-42ea-9292-c399722df899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ANuIbb IdAqtf</value>
      <webElementGuid>8b99f029-a63f-4752-9f4e-04c83941da27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>k4HEge</value>
      <webElementGuid>64261c8d-e5ee-404d-98c3-f4516e849cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6459692e-3c43-462b-8ede-99228c360d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initialView&quot;)/div[@class=&quot;ANuIbb IdAqtf&quot;]</value>
      <webElementGuid>30c2f12f-5866-4175-b9e3-baf7e04a6162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initialView']/div[3]</value>
      <webElementGuid>44aaab44-7ab6-4077-aa18-818711e06d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>ba5c5aa6-76f7-4e69-be9e-79bb7ece7550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
