<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>6de7c0ed-04cb-4b31-839f-2fab742ba1e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf8ba338-15e2-43a2-ad4a-2099e3d269d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> bg-primary-500 cursor-pointer undefined button button-Primary flex justify-center items-center bg-primary-500 h-10 w-auto  rounded font-semibold text-sm text-Basic-0 px-2 md:px-6 undefined  </value>
      <webElementGuid>973eb825-8b6b-4b61-bdd3-9bf1400a9258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>32e51958-e2f2-4978-a60a-ecf566b14303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>bc2fe3b2-a4f6-456d-a156-e1eedbfc8675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex-1 flex overflow-hidden&quot;]/div[@class=&quot;flex-1 overflow-y-auto main-content py-10 px-4 md:px-8 scrollbar scrollbar_for_firefox&quot;]/div[@class=&quot;fixed z-30 inset-0 overflow-y-auto  false&quot;]/div[@class=&quot;flex items-center justify-center h-screen&quot;]/div[@class=&quot;z-40 absolute p-6 mt-24 md:mt-0 mx-2 md:mx-1 overflow-auto inline-block max-h-90 h-auto rounded-lg modalscrollbar bg-white text-left shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-xl w-full undefined&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;flex justify-end gap-2 px-6 pt-4 mt-20 -mx-6 border-t border-gray-200&quot;]/button[@class=&quot;bg-primary-500 cursor-pointer undefined button button-Primary flex justify-center items-center bg-primary-500 h-10 w-auto  rounded font-semibold text-sm text-Basic-0 px-2 md:px-6 undefined&quot;]</value>
      <webElementGuid>3a10f9a5-c7ab-49e4-9e63-3f5a87e3705a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>ef80beb3-c364-4b3c-9159-edafcf41e7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[5]/div/div[2]/form/div[2]/button[2]</value>
      <webElementGuid>fd916cc5-a235-4c07-b905-2d5a33d05252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>284c6800-038f-4ddc-ba66-2d0d05bb8bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Vendor Legal'])[1]/following::button[2]</value>
      <webElementGuid>58722911-39ab-4c47-9559-e0b3a2012173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Vendor Legal - Kishore, Purchase Officer'])[1]/preceding::button[1]</value>
      <webElementGuid>b0d2dcad-1ab1-48fb-ae98-9b121aff1837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>dad4ec0e-23a9-493c-bcfe-4d5e37faba1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>bd48db0e-db61-40f4-9675-a1572201e5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>792949dc-0355-4561-bf0f-9f0ad126e06b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
