<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kishore, Purchase Officer</name>
   <tag></tag>
   <elementGuidId>2b7c3b6c-b975-448b-9ce7-297170760f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-instance-id-contact-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-instance-id-contact-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1f51f99-d525-41a0-9761-53069437fa31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__option select2-selection__option--is-focused css-1dqdw33-option</value>
      <webElementGuid>d7a9787f-dbb9-4476-8c9e-71d3161ce70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>598e930b-42c6-4c9f-9b82-c8232dae2755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-instance-id-contact-option-0</value>
      <webElementGuid>a7af7621-4a39-4993-ba24-a1fd1136ae96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ba76e29e-4991-4beb-99c0-dabaccdf44cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kishore, Purchase Officer</value>
      <webElementGuid>7e521606-e8cd-4d72-9cb6-5c90be56facb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-instance-id-contact-option-0&quot;)</value>
      <webElementGuid>e01c143c-ea67-4b2d-92a9-58c5e80aaf91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-contact-option-0']</value>
      <webElementGuid>09ff702e-dee3-45dd-a844-0bed5d36dbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-contact-listbox']/div/div</value>
      <webElementGuid>c22b526f-1a49-4c66-9768-55d98881ad7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search and select'])[1]/following::div[6]</value>
      <webElementGuid>a45b2946-e972-4751-a138-49b20b320b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[11]</value>
      <webElementGuid>460d4dc4-34ec-4185-b4b9-dc927b8e6216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::div[2]</value>
      <webElementGuid>c60b5af8-134b-4738-9418-7945d3da9b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::div[2]</value>
      <webElementGuid>286cd41a-99c0-4924-94c1-8a8696477b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kishore, Purchase Officer']/parent::*</value>
      <webElementGuid>a10538b4-41a4-4b0f-a8ea-ce3a21c5cd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>099027b0-04db-4d37-b69a-d389e4303531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-instance-id-contact-option-0' and (text() = 'Kishore, Purchase Officer' or . = 'Kishore, Purchase Officer')]</value>
      <webElementGuid>98666318-2d2f-44f9-b8d9-d88a7c35c470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
