<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search and select vendor_select2-select_452e0a</name>
   <tag></tag>
   <elementGuidId>b165ace7-f982-4868-bc35-fcd1d59a4479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[4]/div/div[2]/form/div/div[2]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.select2-selection__input-container.css-ackcql</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fbf97dd8-3785-4e19-9113-65a209472671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__input-container css-ackcql</value>
      <webElementGuid>8361291e-9370-45e9-b452-62e99f5207cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;flex-1 flex overflow-hidden&quot;]/div[@class=&quot;flex-1 overflow-y-auto main-content py-10 px-4 md:px-8 scrollbar scrollbar_for_firefox&quot;]/div[@class=&quot;fixed z-30 inset-0 overflow-y-auto  false&quot;]/div[@class=&quot;flex items-center justify-center h-screen&quot;]/div[@class=&quot;z-40 absolute p-6 mt-24 md:mt-0 mx-2 md:mx-1 overflow-auto inline-block max-h-90 h-auto rounded-lg modalscrollbar bg-white text-left shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-xl w-full undefined&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full css-b62m3t-container&quot;]/div[@class=&quot;select2-selection__control select2-selection__control--is-focused select2-selection__control--menu-is-open css-163nsml-control&quot;]/div[@class=&quot;select2-selection__value-container css-1d8n9bt&quot;]/div[@class=&quot;select2-selection__input-container css-ackcql&quot;]</value>
      <webElementGuid>3097a7a6-9ba8-4559-b179-fbbf76c105cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[4]/div/div[2]/form/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>6d6cea00-be75-4d96-a62b-82647c913f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search and select vendor'])[1]/following::div[1]</value>
      <webElementGuid>176e6218-4241-4951-8f51-7133bad68fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[6]</value>
      <webElementGuid>37ac2a8b-a9a4-4d04-b82f-b8c03f8c8bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AIRTEL PAYMENTS BANK LIMITED'])[1]/preceding::div[3]</value>
      <webElementGuid>f112aa53-ec54-4012-bdfd-3021f7586e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARVIND VIKRAMJEET SHUKLA'])[1]/preceding::div[4]</value>
      <webElementGuid>42391308-5c56-4ff8-947f-d5b24f5b424c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>07b62d9b-049a-4407-9fcd-1363859d02d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
