<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RFQs</name>
   <tag></tag>
   <elementGuidId>bb1fda09-7795-49e2-b6a6-74eaca93a774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[4]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d85857f-dec0-4d2e-aef0-6219737a6e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal text-xs    bodyText   </value>
      <webElementGuid>4358908a-08df-4f86-b404-5d87ffd158a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RFQs</value>
      <webElementGuid>585e6436-9dd3-4a8f-bbe2-58a0d12b2faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;z-30 bg-Gray-900 h-screen overflow-y-auto w-[252px] hidden lg:block no-scrollbar&quot;]/div[@class=&quot;px-6 pb-16 text-[#969696] flex flex-col&quot;]/div[4]/div[@class=&quot;flex pl-2 gap-4 mt-7 cursor-pointer items-center&quot;]/div[@class=&quot;font-normal text-xs    bodyText&quot;]</value>
      <webElementGuid>4fb6e492-3086-4924-8856-7b776d96ebad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[4]/div[2]/div[2]</value>
      <webElementGuid>cf6169d8-0a1e-43c9-9b36-290727c27cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TASKS'])[1]/following::div[3]</value>
      <webElementGuid>07111cff-292a-4e56-b219-7460f9f616d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Quotes'])[1]/following::div[5]</value>
      <webElementGuid>49f6f299-1ff3-4837-9088-c4b62c4177d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Quotations'])[1]/preceding::div[2]</value>
      <webElementGuid>2ff9c294-8f0a-470d-9b55-d5b544a8fac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Quotations'])[1]/preceding::div[5]</value>
      <webElementGuid>f8c07ee2-2702-4bb2-b716-07ba2c099c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RFQs']/parent::*</value>
      <webElementGuid>6ac19a67-a46c-42cb-998f-0df9def5e9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]</value>
      <webElementGuid>7e73a6d5-4588-4de9-bf22-c34ba635dfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RFQs' or . = 'RFQs')]</value>
      <webElementGuid>32e9bc26-9905-4f1e-9a02-727c9a6832ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
