<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Requirements</name>
   <tag></tag>
   <elementGuidId>317542cf-c6e2-4ef3-b709-8f312df1e413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[3]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60be5d03-d3b7-4fc0-912d-1697853847f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex pl-2 gap-4 mt-7 cursor-pointer items-center   </value>
      <webElementGuid>22f4739e-cada-4b21-9653-74980a67524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Requirements</value>
      <webElementGuid>06a5a543-facf-4c40-b158-0afd37e7ed34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;flex h-screen&quot;]/div[@class=&quot;z-30 bg-Gray-900 h-screen overflow-y-auto w-[252px] hidden lg:block no-scrollbar&quot;]/div[@class=&quot;px-6 pb-16 text-[#969696] flex flex-col&quot;]/div[3]/div[@class=&quot;flex pl-2 gap-4 mt-7 cursor-pointer items-center&quot;]</value>
      <webElementGuid>2b303727-f424-4dd2-81eb-c3c0b4bfed4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[3]/div[3]</value>
      <webElementGuid>a2cf68a9-b74c-4b10-872f-12ed87b57174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Projects'])[1]/following::div[1]</value>
      <webElementGuid>0a6e00a8-f454-4af9-949b-6ec7b2343332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROJECTS'])[1]/following::div[4]</value>
      <webElementGuid>9038fe38-afe3-4272-94d7-613d199edca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Quotes'])[1]/preceding::div[4]</value>
      <webElementGuid>9ce534fc-f4c7-4122-8187-a90b9efd8295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>8bffe728-d37b-435c-a848-5fbb3aca34ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Requirements' or . = 'Requirements')]</value>
      <webElementGuid>e203a9cf-e46b-4a51-a4f0-28bcd8ab97df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
