<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Customer_1</name>
   <tag></tag>
   <elementGuidId>2c85af2c-5e48-4d74-9840-860299dada91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-instance-id-customer-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-instance-id-customer-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65795ce4-13dc-44c0-b046-1076abb86fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__option select2-selection__option--is-focused css-1dqdw33-option</value>
      <webElementGuid>1970aa71-efa4-47b4-8ba4-4b7bd80748d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82bc818f-578a-4450-a309-7f68c5d98c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-instance-id-customer-option-0</value>
      <webElementGuid>1ce7bfbc-0efd-4f7a-a4f8-72ed1c943402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7152b99e-78ca-48a9-a3fa-91a32ed20dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Customer</value>
      <webElementGuid>129af6a4-244f-4017-b231-f6863e478897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-instance-id-customer-option-0&quot;)</value>
      <webElementGuid>5f73654e-8681-4cc3-9f37-a0696e58d766</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-customer-option-0']</value>
      <webElementGuid>0d4de1db-a7b3-4a80-994d-63a46aba194c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-customer-listbox']/div/div</value>
      <webElementGuid>e420a1f5-ce0a-498f-bfe2-ace67f7ec573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[11]</value>
      <webElementGuid>86d33c75-e7c3-47a8-a406-228445403fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::div[1]</value>
      <webElementGuid>2e213207-66f8-4c90-bd45-b2ad450ef1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Customer']/parent::*</value>
      <webElementGuid>ce0d951c-eeb8-4adc-bfa9-e33b6ba11fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>0f7c1dd8-8438-465d-bf86-43007fb94820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-instance-id-customer-option-0' and (text() = 'Test Customer' or . = 'Test Customer')]</value>
      <webElementGuid>847a0834-a858-4051-bec2-c237d309f172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
