<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MS TMT Bar 12mm</name>
   <tag></tag>
   <elementGuidId>227b353b-265c-40d2-9b07-2fc22bbcf927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-instance-id-item-option-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-instance-id-item-option-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf1aaba9-9111-4c7a-bfb4-3f9cdd6c9e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__option select2-selection__option--is-focused css-1dqdw33-option</value>
      <webElementGuid>ba82155a-ab87-4311-93cc-2182a531379f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14071f45-0994-4871-b6c8-9e19a179ed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-instance-id-item-option-12</value>
      <webElementGuid>534d9f01-b507-4952-93cc-f1084670e51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1ada5dd2-d4f6-4c2c-89e0-e05af8a3eddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MS TMT Bar 12mm</value>
      <webElementGuid>c7e43474-dbf8-4b7c-b36f-067d78157d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-instance-id-item-option-12&quot;)</value>
      <webElementGuid>6cdbfcf3-d99a-4d65-a4ea-14bad325d009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-item-option-12']</value>
      <webElementGuid>995dbed9-e0c7-4bcb-ac67-a659a7ea088b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-item-listbox']/div/div[13]</value>
      <webElementGuid>33893c21-c7ec-447c-8d0d-4e79d9ebeb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M.S.SQUARE PIPE'])[1]/following::div[1]</value>
      <webElementGuid>82133e65-32c2-4f1f-92eb-849f591a7e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MS Round Bar'])[1]/following::div[2]</value>
      <webElementGuid>974420e4-dcf9-46ae-97b5-22a301fb5934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MS TMT Bar 16mm'])[1]/preceding::div[1]</value>
      <webElementGuid>50fd1c08-6ef1-46f7-b169-2b2f166310c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MS TMT Bar 20mm'])[1]/preceding::div[2]</value>
      <webElementGuid>10180304-2a22-4a2b-9329-f3fc1ebc1cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MS TMT Bar 12mm']/parent::*</value>
      <webElementGuid>33d0a9b8-1992-40f3-b911-2d5e051ee8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]</value>
      <webElementGuid>d6427ad7-03be-46e6-874b-73da60a91d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-instance-id-item-option-12' and (text() = 'MS TMT Bar 12mm' or . = 'MS TMT Bar 12mm')]</value>
      <webElementGuid>58f8be4c-f991-4f5b-8143-c99a932b9510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
