<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Address, Bangalore, Karnataka</name>
   <tag></tag>
   <elementGuidId>1e69f51b-5ba6-4d82-9cf6-bfc90d70ba83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-instance-id-billingAddress-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-instance-id-billingAddress-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f0eb045-9709-419f-80a9-628f4913ee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__option select2-selection__option--is-focused select2-selection__option--is-selected css-1ew0j85-option</value>
      <webElementGuid>ac987c04-504e-4dbd-8332-b88f82cad52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95dc97d4-5a55-4253-8c3a-db220558bf5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-instance-id-billingAddress-option-0</value>
      <webElementGuid>7c74c478-a955-4f92-bf4c-975a31b2ca8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1efb5b83-1f18-4b8a-8d1f-39250c6995ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Test Address, Bangalore, Karnataka</value>
      <webElementGuid>90cecc9a-e345-4d5e-b421-e9a3bb08bc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-instance-id-billingAddress-option-0&quot;)</value>
      <webElementGuid>89a1bad4-c7a6-414f-a70b-681f5a5a3885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-billingAddress-option-0']</value>
      <webElementGuid>81460f01-1811-4c95-886c-020f5ca5f48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-instance-id-billingAddress-listbox']/div/div</value>
      <webElementGuid>59ccf454-f78d-4709-acc0-2a4fb88cbd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office Address - Test Address, , Bangalore Karnataka'])[1]/following::div[6]</value>
      <webElementGuid>bf0facaa-5be8-4b6a-9bbc-6cd9dc7b9104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[11]</value>
      <webElementGuid>3f3fa667-9dc7-45f1-b825-6578359f68b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address details'])[2]/preceding::div[1]</value>
      <webElementGuid>64776ddd-9435-42ed-bd03-ffc85bcc5d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Customer'])[2]/preceding::div[2]</value>
      <webElementGuid>b7f823a4-a974-4a0a-9d67-14eb0be1c839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Address, Bangalore, Karnataka']/parent::*</value>
      <webElementGuid>038107ba-fc7a-49ac-8377-f0dee2275178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>4f41bf07-a173-4d57-9c2c-26881567dd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-instance-id-billingAddress-option-0' and (text() = ' Test Address, Bangalore, Karnataka' or . = ' Test Address, Bangalore, Karnataka')]</value>
      <webElementGuid>7c3ca8b5-4a99-41bb-b4ed-c3a85d64dab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
