<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__quantity</name>
   <tag></tag>
   <elementGuidId>06e76b71-fc8e-437a-bf80-18157f1487ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46e679ba-0ecd-4c62-a014-f59c525fb498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>b412ec92-f82b-4c06-a68a-e090160bc10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>bc826129-0667-4780-86ed-e88dd1e161fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>b4f13988-3fef-4720-9776-ebd99c770f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Quantity</value>
      <webElementGuid>bf20d265-7248-4d84-a334-8e13f816b7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined bg-white textField w-full p-3 text-black border rounded outline-none text-sm transition duration-150 ease-in-out font-normal h-12 border-solid focus:border-2 focus:border-primary-400  placeholder-iron-gray focus:outline-none placeholder-[#A6B0CF]  border-gray-200 hover:border-gray-400 </value>
      <webElementGuid>73a3e287-8367-4745-828e-e4c8f876a637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity&quot;)</value>
      <webElementGuid>a568f4f7-adab-4a46-aff0-caa9fb520d11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity']</value>
      <webElementGuid>2ce1a97e-63e1-45e8-84f2-a36c70470e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div[2]/div/div[3]/div/div[2]/form/div[3]/div[2]/input</value>
      <webElementGuid>0ed39196-0f9b-4d67-9902-56758a642f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>1c14247f-21ba-48e0-864d-dbd67b76026f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'quantity' and @id = 'quantity' and @placeholder = 'Quantity']</value>
      <webElementGuid>6b1aa139-f015-49d8-9a4b-527db7ad3d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
